version: '3'

services:
  prestashop:
    image: yacheto/be_184725
    ports:
      - "18472:443"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 60s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/sqldump.sql
      - ./init.sh:/var/www/html/init.sh
    command: sh -c './init.sh'
    networks:
      - admin-mysql_default
networks:
  admin-mysql_default:
    external: true